// Generated by gencpp from file chess_tracking/BoardString.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_BOARDSTRING_H
#define CHESS_TRACKING_MESSAGE_BOARDSTRING_H

#include <ros/service_traits.h>


#include <chess_tracking/BoardStringRequest.h>
#include <chess_tracking/BoardStringResponse.h>


namespace chess_tracking
{

struct BoardString
{

typedef BoardStringRequest Request;
typedef BoardStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BoardString
} // namespace chess_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chess_tracking::BoardString > {
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::chess_tracking::BoardString&) { return value(); }
};

template<>
struct DataType< ::chess_tracking::BoardString > {
  static const char* value()
  {
    return "chess_tracking/BoardString";
  }

  static const char* value(const ::chess_tracking::BoardString&) { return value(); }
};


// service_traits::MD5Sum< ::chess_tracking::BoardStringRequest> should match
// service_traits::MD5Sum< ::chess_tracking::BoardString >
template<>
struct MD5Sum< ::chess_tracking::BoardStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::BoardString >::value();
  }
  static const char* value(const ::chess_tracking::BoardStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::BoardStringRequest> should match
// service_traits::DataType< ::chess_tracking::BoardString >
template<>
struct DataType< ::chess_tracking::BoardStringRequest>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::BoardString >::value();
  }
  static const char* value(const ::chess_tracking::BoardStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chess_tracking::BoardStringResponse> should match
// service_traits::MD5Sum< ::chess_tracking::BoardString >
template<>
struct MD5Sum< ::chess_tracking::BoardStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::BoardString >::value();
  }
  static const char* value(const ::chess_tracking::BoardStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::BoardStringResponse> should match
// service_traits::DataType< ::chess_tracking::BoardString >
template<>
struct DataType< ::chess_tracking::BoardStringResponse>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::BoardString >::value();
  }
  static const char* value(const ::chess_tracking::BoardStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_BOARDSTRING_H
