// Generated by gencpp from file chess_tracking/BoardStringResponse.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_BOARDSTRINGRESPONSE_H
#define CHESS_TRACKING_MESSAGE_BOARDSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess_tracking
{
template <class ContainerAllocator>
struct BoardStringResponse_
{
  typedef BoardStringResponse_<ContainerAllocator> Type;

  BoardStringResponse_()
    : output()  {
    }
  BoardStringResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::chess_tracking::BoardStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_tracking::BoardStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BoardStringResponse_

typedef ::chess_tracking::BoardStringResponse_<std::allocator<void> > BoardStringResponse;

typedef boost::shared_ptr< ::chess_tracking::BoardStringResponse > BoardStringResponsePtr;
typedef boost::shared_ptr< ::chess_tracking::BoardStringResponse const> BoardStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_tracking::BoardStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chess_tracking::BoardStringResponse_<ContainerAllocator1> & lhs, const ::chess_tracking::BoardStringResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chess_tracking::BoardStringResponse_<ContainerAllocator1> & lhs, const ::chess_tracking::BoardStringResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chess_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::BoardStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::BoardStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::BoardStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::chess_tracking::BoardStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_tracking/BoardStringResponse";
  }

  static const char* value(const ::chess_tracking::BoardStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
;
  }

  static const char* value(const ::chess_tracking::BoardStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoardStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_tracking::BoardStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_tracking::BoardStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_BOARDSTRINGRESPONSE_H
