// Generated by gencpp from file chess_tracking/Screenshot.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_SCREENSHOT_H
#define CHESS_TRACKING_MESSAGE_SCREENSHOT_H

#include <ros/service_traits.h>


#include <chess_tracking/ScreenshotRequest.h>
#include <chess_tracking/ScreenshotResponse.h>


namespace chess_tracking
{

struct Screenshot
{

typedef ScreenshotRequest Request;
typedef ScreenshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Screenshot
} // namespace chess_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chess_tracking::Screenshot > {
  static const char* value()
  {
    return "b4274f524cc812fc54ca8ebeeda2deb2";
  }

  static const char* value(const ::chess_tracking::Screenshot&) { return value(); }
};

template<>
struct DataType< ::chess_tracking::Screenshot > {
  static const char* value()
  {
    return "chess_tracking/Screenshot";
  }

  static const char* value(const ::chess_tracking::Screenshot&) { return value(); }
};


// service_traits::MD5Sum< ::chess_tracking::ScreenshotRequest> should match
// service_traits::MD5Sum< ::chess_tracking::Screenshot >
template<>
struct MD5Sum< ::chess_tracking::ScreenshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::Screenshot >::value();
  }
  static const char* value(const ::chess_tracking::ScreenshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::ScreenshotRequest> should match
// service_traits::DataType< ::chess_tracking::Screenshot >
template<>
struct DataType< ::chess_tracking::ScreenshotRequest>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::Screenshot >::value();
  }
  static const char* value(const ::chess_tracking::ScreenshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chess_tracking::ScreenshotResponse> should match
// service_traits::MD5Sum< ::chess_tracking::Screenshot >
template<>
struct MD5Sum< ::chess_tracking::ScreenshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::Screenshot >::value();
  }
  static const char* value(const ::chess_tracking::ScreenshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::ScreenshotResponse> should match
// service_traits::DataType< ::chess_tracking::Screenshot >
template<>
struct DataType< ::chess_tracking::ScreenshotResponse>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::Screenshot >::value();
  }
  static const char* value(const ::chess_tracking::ScreenshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_SCREENSHOT_H
