// Generated by gencpp from file chess_tracking/StringAndFloatsGrid.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_STRINGANDFLOATSGRID_H
#define CHESS_TRACKING_MESSAGE_STRINGANDFLOATSGRID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess_tracking
{
template <class ContainerAllocator>
struct StringAndFloatsGrid_
{
  typedef StringAndFloatsGrid_<ContainerAllocator> Type;

  StringAndFloatsGrid_()
    : name()
    , x()
    , y()
    , z()  {
    }
  StringAndFloatsGrid_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> const> ConstPtr;

}; // struct StringAndFloatsGrid_

typedef ::chess_tracking::StringAndFloatsGrid_<std::allocator<void> > StringAndFloatsGrid;

typedef boost::shared_ptr< ::chess_tracking::StringAndFloatsGrid > StringAndFloatsGridPtr;
typedef boost::shared_ptr< ::chess_tracking::StringAndFloatsGrid const> StringAndFloatsGridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator1> & lhs, const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator1> & lhs, const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chess_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61d312837c8724f6803b15d9751ac361";
  }

  static const char* value(const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61d312837c8724f6ULL;
  static const uint64_t static_value2 = 0x803b15d9751ac361ULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_tracking/StringAndFloatsGrid";
  }

  static const char* value(const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StringAndFloatsGrid.msg\n"
"string[] name\n"
"float32[] x\n"
"float32[] y\n"
"float32[] z\n"
;
  }

  static const char* value(const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringAndFloatsGrid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_tracking::StringAndFloatsGrid_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_STRINGANDFLOATSGRID_H
