// Generated by gencpp from file chess_tracking/TransformPoint.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_TRANSFORMPOINT_H
#define CHESS_TRACKING_MESSAGE_TRANSFORMPOINT_H

#include <ros/service_traits.h>


#include <chess_tracking/TransformPointRequest.h>
#include <chess_tracking/TransformPointResponse.h>


namespace chess_tracking
{

struct TransformPoint
{

typedef TransformPointRequest Request;
typedef TransformPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TransformPoint
} // namespace chess_tracking


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chess_tracking::TransformPoint > {
  static const char* value()
  {
    return "3ee7093c6df18d4364892f198e4fb79b";
  }

  static const char* value(const ::chess_tracking::TransformPoint&) { return value(); }
};

template<>
struct DataType< ::chess_tracking::TransformPoint > {
  static const char* value()
  {
    return "chess_tracking/TransformPoint";
  }

  static const char* value(const ::chess_tracking::TransformPoint&) { return value(); }
};


// service_traits::MD5Sum< ::chess_tracking::TransformPointRequest> should match
// service_traits::MD5Sum< ::chess_tracking::TransformPoint >
template<>
struct MD5Sum< ::chess_tracking::TransformPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::TransformPoint >::value();
  }
  static const char* value(const ::chess_tracking::TransformPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::TransformPointRequest> should match
// service_traits::DataType< ::chess_tracking::TransformPoint >
template<>
struct DataType< ::chess_tracking::TransformPointRequest>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::TransformPoint >::value();
  }
  static const char* value(const ::chess_tracking::TransformPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chess_tracking::TransformPointResponse> should match
// service_traits::MD5Sum< ::chess_tracking::TransformPoint >
template<>
struct MD5Sum< ::chess_tracking::TransformPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chess_tracking::TransformPoint >::value();
  }
  static const char* value(const ::chess_tracking::TransformPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_tracking::TransformPointResponse> should match
// service_traits::DataType< ::chess_tracking::TransformPoint >
template<>
struct DataType< ::chess_tracking::TransformPointResponse>
{
  static const char* value()
  {
    return DataType< ::chess_tracking::TransformPoint >::value();
  }
  static const char* value(const ::chess_tracking::TransformPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_TRANSFORMPOINT_H
