// Generated by gencpp from file chess_tracking/TransformPointRequest.msg
// DO NOT EDIT!


#ifndef CHESS_TRACKING_MESSAGE_TRANSFORMPOINTREQUEST_H
#define CHESS_TRACKING_MESSAGE_TRANSFORMPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace chess_tracking
{
template <class ContainerAllocator>
struct TransformPointRequest_
{
  typedef TransformPointRequest_<ContainerAllocator> Type;

  TransformPointRequest_()
    : input_point()  {
    }
  TransformPointRequest_(const ContainerAllocator& _alloc)
    : input_point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _input_point_type;
  _input_point_type input_point;





  typedef boost::shared_ptr< ::chess_tracking::TransformPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_tracking::TransformPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TransformPointRequest_

typedef ::chess_tracking::TransformPointRequest_<std::allocator<void> > TransformPointRequest;

typedef boost::shared_ptr< ::chess_tracking::TransformPointRequest > TransformPointRequestPtr;
typedef boost::shared_ptr< ::chess_tracking::TransformPointRequest const> TransformPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_tracking::TransformPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chess_tracking::TransformPointRequest_<ContainerAllocator1> & lhs, const ::chess_tracking::TransformPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_point == rhs.input_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chess_tracking::TransformPointRequest_<ContainerAllocator1> & lhs, const ::chess_tracking::TransformPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chess_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_tracking::TransformPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_tracking::TransformPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_tracking::TransformPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46e1a079c4b17e399923559c1363c355";
  }

  static const char* value(const ::chess_tracking::TransformPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46e1a079c4b17e39ULL;
  static const uint64_t static_value2 = 0x9923559c1363c355ULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_tracking/TransformPointRequest";
  }

  static const char* value(const ::chess_tracking::TransformPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# TransformPoint.srv\n"
"geometry_msgs/Point input_point\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::chess_tracking::TransformPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransformPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_tracking::TransformPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_tracking::TransformPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.input_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_TRACKING_MESSAGE_TRANSFORMPOINTREQUEST_H
