(cl:defpackage chess_tracking-srv
  (:use )
  (:export
   "BOARDSTRING"
   "<BOARDSTRING-REQUEST>"
   "BOARDSTRING-REQUEST"
   "<BOARDSTRING-RESPONSE>"
   "BOARDSTRING-RESPONSE"
   "PIECEMATCHES"
   "<PIECEMATCHES-REQUEST>"
   "PIECEMATCHES-REQUEST"
   "<PIECEMATCHES-RESPONSE>"
   "PIECEMATCHES-RESPONSE"
   "SCREENSHOT"
   "<SCREENSHOT-REQUEST>"
   "SCREENSHOT-REQUEST"
   "<SCREENSHOT-RESPONSE>"
   "SCREENSHOT-RESPONSE"
   "TRANSFORMPOINT"
   "<TRANSFORMPOINT-REQUEST>"
   "TRANSFORMPOINT-REQUEST"
   "<TRANSFORMPOINT-RESPONSE>"
   "TRANSFORMPOINT-RESPONSE"
  ))

