(cl:defpackage chess_tracking-srv
  (:use )
  (:export
   "BOARDSTRING"
   "<BOARDSTRING-REQUEST>"
   "BOARDSTRING-REQUEST"
   "<BOARDSTRING-RESPONSE>"
   "BOARDSTRING-RESPONSE"
   "TRANSFORMPOINT"
   "<TRANSFORMPOINT-REQUEST>"
   "TRANSFORMPOINT-REQUEST"
   "<TRANSFORMPOINT-RESPONSE>"
   "TRANSFORMPOINT-RESPONSE"
  ))

